apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: all-services
  namespace: cinevision
spec:
  host: "*.cinevision.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL