apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"