apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://rootuser:rootpass@mongodb-service:27017/user?authSource=admin"