apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cinevision
resources:
  - namespaces/cinevision-ns.yaml
  - deployments/api-gateway-deployment.yaml
  - services/api-gateway-svc.yaml
  - deployments/user-service-deployment.yaml
  - services/user-service-svc.yaml
  - deployments/movie-service-deployment.yaml
  - services/movie-service-svc.yaml
  - deployments/email-service-deployment.yaml
  - services/email-service-svc.yaml
  - deployments/eureka-server-deployment.yaml
  - services/eureka-server-svc.yaml
  - deployments/frontend-deployment.yaml 
  - services/frontend-svc.yaml
  - monitoring/api-gateway-servicemonitor.yaml
  - monitoring/user-service-servicemonitor.yaml
  - monitoring/movie-service-servicemonitor.yaml
  - monitoring/email-service-servicemonitor.yaml
  - monitoring/eureka-server-servicemonitor.yaml
  - istio/virtualservice-api-gateway.yaml
  - istio/destinationrule-all.yaml
  - istio/gateway.yaml
  - istio/virtualservice-ingress.yaml