apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 1
  name: api-gateway
- count: 1
  name: user-service
- count: 1
  name: movie-service
- count: 1
  name: email-service
- count: 1
  name: eureka-server
- count: 1
  name: frontend
resources:
- ../../base
images:
- name: api-gateway
  newName: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway
  newTag: 67a551e
- name: email-service
  newName: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/email-service
  newTag: 67a551e
- name: eureka-server
  newName: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/eureka-server
  newTag: 67a551e
