apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
      - name: user-service
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/user-service:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  template:
    spec:
      containers:
      - name: movie-service
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/movie-service:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  template:
    spec:
      containers:
      - name: email-service
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/email-service:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  template:
    spec:
      containers:
      - name: eureka-server
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/eureka-server:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cinevision/frontend:latest