apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- replicas-patch.yaml
- image-tags-patch.yaml
images:
- name: api-gateway
  newName: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway
  newTag: a5b7b6d
