apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - replicas-patch.yaml
patchesStrategicMerge:
- image-tags-patch.yaml

images:
- name: api-gateway
  newName: 590396427103.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway
  newTag: c88c00c
resources:
- ../../base
